atlassian:
  confluenceUrl:  https://user.atlassian.net/wiki
  jiraUrl:  https://user.atlassian.net/
  username: james
  password: 'password'
  spaceKey: Deployment
    projects:
    - TEST
    - PROJ
    - NEAT
github:
  host: api.github.com
  pathPrefix: ''
  access_token: access-token
repos:
  - {username: 'username', repo: 'repo-name'}
  - {username: 'username', repo: 'repo-name'}
  - {username: 'username', repo: 'repo-name'}
  - {username: 'username', repo: 'repo-name'}
  - {username: 'username', repo: 'repo-name'}
  - {username: 'username', repo: 'repo-name'}
